services:
  - type: web
    name: shadowsocks
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SS_PASSWORD
        value: "Ethan@092709"   # इसे बदलना न भूलें
      - key: SS_METHOD
        value: "chacha20-ietf-poly1305"
      - key: SS_PORT
        value: "8388"
    ports:
      - port: 8388
        protocol: tcp
      - port: 8388
        protocol: udp
